### ISSUE TITLE
반응형 레이아웃 body container 사이즈 변경 요청

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-frontend#3]
### 현재 테블릿S 일 때 body container 상태
![image](https://user-images.githubusercontent.com/35598710/134441123-fa5d58b0-c80b-4a6f-8f78-e8a8b79a1a98.png)

<br/><br/>
#### 지금은 모바일(479px인가) 일 때 width가 100%가 되도록 되어 있는데 이것을 테블릿S일 때부터 100%가 되도록 수정해주세요 ㅎㅎ

**Comment by thsuekfk2** [comment]
네
