### ISSUE TITLE
메뉴바 리팩토링

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-frontend#31]
# 시험 끝나고 해주세용

1. 컴포넌트 재활용
![image](https://user-images.githubusercontent.com/35598710/137598260-a55d3524-b5e2-472d-b0b2-a96dd2141354.png)
현재는 알림 버튼-아이콘 로그인 버튼-아이콘 등이 반응형 별로 다른 태그로 묶여있는데 이를 통합해 하나의 태그에서 css 반응형을 이용해 라우팅 해도록 수정해주세요

2. 로그인 버튼 실종 문제 해결
로그인 버튼, 알림 버튼이 모바일에서 안보이는 문제..!

3. 사이드바 하단부쪽에 배경색이 풀충전 되지 않는 문제
height가 100%가 아닌듯..?!

**Comment by thsuekfk2** [comment]
완료했습니다 확인 부탁~!~

**Comment by suhongkim98** [comment]
구욷!
