### ISSUE TITLE
알림 팝업 창 구현

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-frontend#4]
현재 백그라운드 알림의 경우 정상적으로 팝업창 형태로 뜨지만 포어그라운드 상태에서는 FCM알림이 올 경우 콘솔로그로 찍히게끔 되어있습니다. 

포어그라운드 상태에서도 백그라운드처럼 팝업창이 뜨게끔 해주세요~

### 현재 정상적으로 작동하는 백그라운드 알림 코드(public/firebase-messaging-sw.js)
![image](https://user-images.githubusercontent.com/35598710/134533957-b025a02b-39a1-4178-8ae3-0c3c9e7ba03d.png)

### 현재 포어그라운드 알림 코드(main.js)
![image](https://user-images.githubusercontent.com/35598710/134534105-38e25d31-22f3-4f21-95e2-491661d54c9a.png)

### 방법 https://scorpio-mercury.tistory.com/14
![image](https://user-images.githubusercontent.com/35598710/134534442-0a9af41f-e4cb-4476-b606-6f38f7091b2e.png)

**Comment by thsuekfk2** [comment]
확인
