### ISSUE TITLE
보안 취약점 문제 해결

### ISSUE THREAD

**Issue by suhongkim98** [1sTeam/all-knu-frontend#7]
![image](https://user-images.githubusercontent.com/35598710/134711744-fc2fd484-f35c-4dde-8d70-9b18fee1f78b.png)

누군가의 npm, node 버전이 굉장히 낮아서 생긴 문제인듯 하오니 각각 최신 버전으로 모두 업데이트 해주고 블로그 링크 따라 해결해주세여
https://wonyong-jang.github.io/git/2020/05/08/Github-dependency.html

**Comment by thsuekfk2** [comment]
다 업데이트 다 했는데도 안되는데 도와주세요,,,
